stages:
  - docker

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

image: docker:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

docker-build:
  stage: docker
  script:
    - docker build -f ./Source/Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
