default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

build:
  stage: build
  before_script:
    - docker info
    - printenv
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin 

  script:
    - docker build -f ./Source/Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
