stages:
  - docker

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375 

services:
  - name: docker:dind
    command: ["--host=tcp://0.0.0.0:2375"] 

image: docker:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

docker-build:
  stage: docker
  script:
    - docker build -f ./Source/Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
